baseurl = "https://madicetea.me"
title = "Welcome to Alex's website"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
	
[params]
	avatarurl = "images/avatar.jpg"	
	favicon_32 = "images/favicon-32x32.png"
	favicon_16 = "images/favicon-16x16.png"
	
# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/madicetea/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/mrlogicalalex/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope-open fa-2x"
    weight = 3
    url = "mailto:hello@madicetea.me"
[[params.social]]
    name = "Resume"
    icon = "far fa-file-pdf fa-2x"
    weight = 4
	url = "https://madicetea.me/resume/Wiegman_2019.09_Resume.pdf"
[[params.social]]
    name = "Location"
    icon = "fas fa-map-marker-alt fa-2x"
    weight = 5
	url = "https://www.google.com/maps/place/Modesto,+CA/@37.6532641,-121.0586931,12z?hl=en"	
	
	
[languages]
    [languages.en]
        languagename = "English"
        title = "Alex's Website"

        [languages.en.params]
		author = "Alex W. (T.)"
		info = "Recent graduate of the University of Tokyo currently seeking full-time employment. Passionate in Cybersecurity, Website and Software Development, and Network Engineering."
		description = "Alex's personal website"
		keywords = "personal, resume, webdev, network, opsec, deveops, neural networks, Python, TensorFlow"

		footercontent = "Copyright MadIcetea. 2018-"

		hidecredits = true
		hidecopyright = true

		rtl = false
		math = false

        [languages.en.menu]

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Contact Me"
        weight = 2.0
        url = "/contact/"
		
        [[languages.en.menu.main]]
        name = "Blog"
        weight = 3.0
        url = "/posts/"

    [languages.ja]
        languagename = "日本語"
        title = "アレックスのホームページ"

        [languages.ja.params]
			author = "谷口 アレックス"
			info = "東京大学を卒業しました。現在はウェブ・ソフト・システムズ開発者、サイバーセキュリティの仕事をお探し中です。"
			description = "アレックスのホームページ"
			keywords = "パーソナル, 履歴書, ウェブ, ネットワーク, 開発, サイバーセキュリティ, パイソン, 深層ネットワーク、テンサーフロー"
			footercontent = "このサイトについては「MadIceTea」から許可のない、無断転載を著作権侵害上で禁じる。 2018-。"

			hidecredits = true
			hidecopyright = true

			rtl = false
			math = false

        [languages.ja.menu]

        [[languages.ja.menu.main]]
        name = "私について"
        weight = 1.0
        url = "/ja/jikoshoukai/"
